import json
import os
from pathlib import Path
from typing import List, Dict, Optional
from jinja2 import Template
from loguru import logger

class AppGenerator:
    def __init__(self, output_dir: str = "./workspace/apps"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_app(self, project_name: str, selected_units: List[Dict], description: str = "") -> Dict:
        app_dir = self.output_dir / project_name
        app_dir.mkdir(parents=True, exist_ok=True)

        main_py = self._generate_main_py(project_name, selected_units)
        frontend_html = self._generate_frontend(project_name, selected_units)
        requirements = self._generate_requirements(selected_units)
        pyproject = self._generate_pyproject(project_name)

        (app_dir / "main.py").write_text(main_py, encoding="utf-8")
        (app_dir / "requirements.txt").write_text(requirements, encoding="utf-8")
        (app_dir / "pyproject.toml").write_text(pyproject, encoding="utf-8")

        static_dir = app_dir / "static"
        static_dir.mkdir(exist_ok=True)
        (static_dir / "index.html").write_text(frontend_html, encoding="utf-8")

        src_dir = app_dir / "src" / project_name.replace("-", "_").replace(" ", "_")
        src_dir.mkdir(parents=True, exist_ok=True)

        for unit in selected_units:
            unit_file = src_dir / f"{unit['type']}_{unit['name'].replace('.', '_')}.py"
            content = f'"""\n{unit["description"]}\nOriginal: {unit["original_file"]}\n"""\n\n'
            content += unit["source"]
            unit_file.write_text(content, encoding="utf-8")

        init_file = src_dir / "__init__.py"
        init_file.write_text("", encoding="utf-8")

        logger.info(f"Generated app scaffold at {app_dir}")
        return {
            "path": str(app_dir),
            "main_py": main_py,
            "frontend": frontend_html,
            "requirements": requirements,
            "selected_count": len(selected_units),
        }

    def _generate_main_py(self, project_name: str, selected_units: List[Dict]) -> str:
        module_name = project_name.replace("-", "_").replace(" ", "_")
        imports = []
        classes = []
        functions = []
        entry_points = []

        for unit in selected_units:
            if unit["type"] == "class":
                imports.append(f"from src.{module_name}.{unit['type']}_{unit['name'].replace('.', '_')} import {unit['name'].split('.')[0]}")
                classes.append(unit["name"].split(".")[0])
            elif unit["type"] == "function":
                imports.append(f"from src.{module_name}.{unit['type']}_{unit['name'].replace('.', '_')} import {unit['name']}")
                functions.append(unit["name"])

        import_block = "\n".join(sorted(set(imports)))

        template = Template('''
import logging
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
import uvicorn
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

{{ import_block }}

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="{{ project_name }}", description="{{ description }}")
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="static")


@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})


@app.get("/api/health")
async def health():
    return {"status": "ok", "units": {{ selected_count }}}


{% for func in functions %}
@app.get("/api/{{ func }}")
async def call_{{ func }}():
    try:
        result = {{ func }}()
        return JSONResponse(content={"result": str(result)})
    except Exception as e:
        return JSONResponse(content={"error": str(e)}, status_code=500)

{% endfor %}
{% for cls in classes %}
@app.post("/api/{{ cls }}/invoke")
async def invoke_{{ cls }():
    try:
        instance = {{ cls }}()
        result = str(instance)
        return JSONResponse(content={"result": result})
    except Exception as e:
        return JSONResponse(content={"error": str(e)}, status_code=500)

{% endfor %}
if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
''')
        return template.render(
            project_name=project_name,
            description=description or "Generated by RepoForge",
            import_block=import_block,
            selected_count=len(selected_units),
            functions=functions[:10],
            classes=classes[:10],
        )

    def _generate_frontend(self, project_name: str, selected_units: List[Dict]) -> str:
        units_json = json.dumps([{"name": u["name"], "type": u["type"], "description": u["description"]} for u in selected_units[:20]])
        template = Template('''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ project_name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; min-height: 100vh; }
        .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
        header { text-align: center; padding: 3rem 0; }
        h1 { font-size: 2.5rem; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        .subtitle { color: #94a3b8; margin-top: 0.5rem; }
        .units-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1.5rem; margin-top: 2rem; }
        .unit-card { background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 1.5rem; transition: transform 0.2s, box-shadow 0.2s; }
        .unit-card:hover { transform: translateY(-4px); box-shadow: 0 10px 40px rgba(0,0,0,0.3); }
        .unit-type { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
        .type-class { background: #7c3aed33; color: #a78bfa; }
        .type-function { background: #05966933; color: #34d399; }
        .type-method { background: #d9770633; color: #fbbf24; }
        .unit-name { font-size: 1.25rem; font-weight: 600; margin: 0.75rem 0 0.5rem; color: #f1f5f9; }
        .unit-desc { color: #94a3b8; font-size: 0.875rem; line-height: 1.5; }
        .unit-meta { display: flex; gap: 1rem; margin-top: 1rem; padding-top: 1rem; border-top: 1px solid #334155; font-size: 0.75rem; color: #64748b; }
        .status { display: inline-flex; align-items: center; gap: 0.5rem; padding: 0.5rem 1rem; border-radius: 8px; font-size: 0.875rem; margin-top: 2rem; }
        .status-ok { background: #05966933; color: #34d399; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{{ project_name }}</h1>
            <p class="subtitle">Generated by RepoForge - {{ units|length }} code units loaded</p>
            <div class="status status-ok">System Ready</div>
        </header>
        <div class="units-grid">
            {% for unit in units %}
            <div class="unit-card">
                <span class="unit-type type-{{ unit.type }}">{{ unit.type }}</span>
                <div class="unit-name">{{ unit.name }}</div>
                <div class="unit-desc">{{ unit.description }}</div>
                <div class="unit-meta">
                    <span>Lines {{ unit.line_start }}-{{ unit.line_end }}</span>
                    <span>{{ unit.complexity }} complexity</span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>
        ''')
        return template.render(project_name=project_name, units=selected_units, selected_count=len(selected_units))

    def _generate_requirements(self, selected_units: List[Dict]) -> str:
        all_imports = set()
        for unit in selected_units:
            for imp in unit.get("imports", []):
                all_imports.add(imp)
        stdlib = {"os", "sys", "json", "re", "math", "datetime", "pathlib", "collections", "itertools", "functools", "typing", "dataclasses", "enum", "abc", "statistics", "random", "string", "time", "hashlib", "base64", "io", "csv", "sqlite3", "http", "urllib", "email", "xml", "html", "logging", "argparse", "configparser", "socket", "selectors", "ssl", "hashlib", "secrets", "getpass", "tempfile", "shutil", "glob", "fnmatch", "linecache", "textwrap", "string", "struct", "codecs", "unicodedata", "reprlib", "pprint", "copy", "pprint", "enum", "graphlib"}
        third_party = all_imports - stdlib
        base = ["fastapi==0.104.1", "uvicorn==0.24.0", "jinja2==3.1.2", "python-multipart==0.0.6"]
        for pkg in sorted(third_party):
            base.append(pkg)
        return "\n".join(base)

    def _generate_pyproject(self, project_name: str) -> str:
        module_name = project_name.replace("-", "_").replace(" ", "_")
        return f'''
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "Generated by RepoForge"
authors = [{{name = "RepoForge", email = "forge@repo.ai"}}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.briefcase]
project_name = "{project_name}"
bundle = "com.repoforge"

[tool.briefcase.app.{module_name}]
formal_name = "{project_name}"
description = "Generated by RepoForge"
long_description = "App generated from cloned repository code units."
requires = ["fastapi", "uvicorn"]
test_suite = "tests"
'''
